# Generated by Django 5.0.1 on 2024-01-29 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-priority', '-updated', '-created', '-task_complete']},
        ),
    ]
